# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConveyorUI-1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ConveyorTemp import Ui_TempWindow
from ConveyorSpeed import Ui_SpeedWindow
from time import sleep


class Ui_MonitoringWindow(object):

    def openTempWindow(self):
        self.MonitoringWindow.close() 
        sleep(0.1)
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_TempWindow()
        self.ui.setupUi(self.window)
        self.ui.center(self.window)
        self.window.show()

    def openSpeedWindow(self):
        self.MonitoringWindow.close() 
        sleep(0.1)
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SpeedWindow()
        self.ui.setupUi(self.window)
        self.ui.center(self.window)
        self.window.show()

    def center(self, window):
        screen = QtWidgets.QDesktopWidget().screenGeometry()
        size = window.geometry()
        x = (screen.width() - size.width()) // 2
        y = (screen.height() - size.height()) // 2
        window.move(x, y)

    def setupUi(self, MonitoringWindow):

        MonitoringWindow.setObjectName("MonitoringWindow")
        MonitoringWindow.resize(1024, 530)
        MonitoringWindow.setWindowOpacity(1.0)
        MonitoringWindow.setLayoutDirection(QtCore.Qt.LeftToRight)

        self.MonitoringWindow = MonitoringWindow

        self.centralwidget = QtWidgets.QWidget(MonitoringWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBoxSpeed = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSpeed.setGeometry(QtCore.QRect(10, 10, 451, 161))
        self.groupBoxSpeed.setObjectName("groupBoxSpeed")
        self.SpeedGraph1 = QtWidgets.QWidget(self.groupBoxSpeed)
        self.SpeedGraph1.setGeometry(QtCore.QRect(0, 20, 451, 141))
        self.SpeedGraph1.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.SpeedGraph1.setObjectName("SpeedGraph1")

        self.groupBoxTemp = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxTemp.setGeometry(QtCore.QRect(10, 180, 451, 161))
        self.groupBoxTemp.setObjectName("groupBoxTemp")
        self.TempGraph1 = QtWidgets.QWidget(self.groupBoxTemp)
        self.TempGraph1.setGeometry(QtCore.QRect(0, 20, 451, 141))
        self.TempGraph1.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.TempGraph1.setObjectName("TempGraph1")

        self.groupBoxVb1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxVb1.setGeometry(QtCore.QRect(480, 10, 431, 161))
        self.groupBoxVb1.setObjectName("groupBoxVb1")
        self.VibGraph1 = QtWidgets.QWidget(self.groupBoxVb1)
        self.VibGraph1.setGeometry(QtCore.QRect(0, 20, 431, 141))
        self.VibGraph1.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.VibGraph1.setObjectName("VibGraph1")

        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(920, 10, 101, 501))
        self.groupBox_6.setObjectName("groupBox_6")
        self.TempBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.TempBtn.setGeometry(QtCore.QRect(10, 30, 80, 115))
        font = QtGui.QFont()
        font.setKerning(True)

        self.TempBtn.setFont(font)
        self.TempBtn.setAutoFillBackground(False)
        self.TempBtn.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.TempBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/icons8-temperature-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TempBtn.setIcon(icon)
        self.TempBtn.setIconSize(QtCore.QSize(50, 50))
        self.TempBtn.setShortcut("")
        self.TempBtn.setCheckable(False)
        self.TempBtn.setObjectName("TempBtn")

        self.TempBtn.clicked.connect(self.openTempWindow)
    


        self.SpeedBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.SpeedBtn.setGeometry(QtCore.QRect(10, 150, 80, 115))
        self.SpeedBtn.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.SpeedBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/icons8-speed-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SpeedBtn.setIcon(icon1)
        self.SpeedBtn.setIconSize(QtCore.QSize(50, 50))
        self.SpeedBtn.setObjectName("SpeedBtn")
        self.SpeedBtn.clicked.connect(self.openSpeedWindow)

        self.ExitBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.ExitBtn.setGeometry(QtCore.QRect(10, 390, 80, 101))
        self.ExitBtn.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.ExitBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/icons8-exit-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitBtn.setIcon(icon2)
        self.ExitBtn.setIconSize(QtCore.QSize(50, 50))
        self.ExitBtn.setObjectName("ExitBtn")
        self.ExitBtn.clicked.connect(MonitoringWindow.close)

        self.groupBoxVb2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxVb2.setGeometry(QtCore.QRect(480, 180, 431, 161))
        self.groupBoxVb2.setObjectName("groupBoxVb2")
        self.VibGraph2 = QtWidgets.QWidget(self.groupBoxVb2)
        self.VibGraph2.setGeometry(QtCore.QRect(0, 20, 431, 141))
        self.VibGraph2.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.VibGraph2.setObjectName("VibGraph2")
        self.groupBoxVb3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxVb3.setGeometry(QtCore.QRect(480, 350, 431, 161))
        self.groupBoxVb3.setObjectName("groupBoxVb3")
        self.VibGraph3 = QtWidgets.QWidget(self.groupBoxVb3)
        self.VibGraph3.setGeometry(QtCore.QRect(0, 20, 431, 141))
        self.VibGraph3.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.VibGraph3.setObjectName("VibGraph3")
        self.groupBoxExecute = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxExecute.setGeometry(QtCore.QRect(10, 350, 461, 161))
        self.groupBoxExecute.setObjectName("groupBoxExecute")
        self.RunBtn = QtWidgets.QPushButton(self.groupBoxExecute)
        self.RunBtn.setGeometry(QtCore.QRect(10, 30, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RunBtn.setFont(font)
        self.RunBtn.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.RunBtn.setObjectName("RunBtn")
        self.StopBtn = QtWidgets.QPushButton(self.groupBoxExecute)
        self.StopBtn.setGeometry(QtCore.QRect(240, 30, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.StopBtn.setFont(font)
        self.StopBtn.setStyleSheet("background-color: rgb(237, 51, 59);")
        self.StopBtn.setObjectName("StopBtn")
        MonitoringWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MonitoringWindow)
        QtCore.QMetaObject.connectSlotsByName(MonitoringWindow)

    def retranslateUi(self, MonitoringWindow):
        _translate = QtCore.QCoreApplication.translate
        MonitoringWindow.setWindowTitle(_translate("MonitoringWindow", "Controls - Monitoring"))
        self.groupBoxSpeed.setTitle(_translate("MonitoringWindow", "Speed"))
        self.groupBoxTemp.setTitle(_translate("MonitoringWindow", "Temperature °C"))
        self.groupBoxVb1.setTitle(_translate("MonitoringWindow", "Vibration 1"))
        self.groupBox_6.setTitle(_translate("MonitoringWindow", "Menu"))
        self.groupBoxVb2.setTitle(_translate("MonitoringWindow", "Vibration 2"))
        self.groupBoxVb3.setTitle(_translate("MonitoringWindow", "Vibration 3"))
        self.groupBoxExecute.setTitle(_translate("MonitoringWindow", "Execute"))
        self.RunBtn.setText(_translate("MonitoringWindow", "RUN"))
        self.StopBtn.setText(_translate("MonitoringWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MonitoringWindow = QtWidgets.QMainWindow()
    ui = Ui_MonitoringWindow()
    ui.setupUi(MonitoringWindow)
    ui.center(MonitoringWindow)
    MonitoringWindow.show()
    sys.exit(app.exec_())
